### ISSUE TITLE
Allow usage of CTRL+SHIFT+P then search for the command name instead of using shortcuts. 

### ISSUE THREAD

**Issue by ajcastro** [ivangabriele/vscode-git-automator#3] opened 2018-10-22 03:16 UTC
I am used to CTRL+SHIFT+P then search for the command name instead of using shortcuts. 
Also this way, I can still use the default shortcut bindings of vscode

**Comment by ivangabriele** [comment] 2018-10-22 10:26
Duplicate of #2

**Closed as completed by ivangabriele** 2018-10-22 10:26 UTC
Labels: duplicate
